feature: ['feature-*', 'feat-*', 'feature/*', 'feat/*']
bugfix: ['fix-*', 'bugfix-*', 'fix/*', 'bugfix/*', 'hotfix/*']
chore: ['chore-*', 'chore/*']
skip-changelog: ['release-*', 'release/*']
documentation: ['documentation/*', 'doc/*']