name: Run Tests
on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
  push:
    branches:
      - 'main'
      - 'dev'

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: NPM Audit
        run: npm audit

      - name: Run Tests and Lint
        run: npm test
